### ISSUE TITLE
the parameter of `onChange` is wrong when I click cancel button in `RangePicker`

### ISSUE THREAD

**Issue by tnyo43** [react-component/picker#757]
# Production like

https://codesandbox.io/p/sandbox/rc-range-picker-onclick-fg9q9p?file=%2Fsrc%2FApp.tsx%3A1%2C1-21%2C1

### Steps to reproduce

1. open the reproduction
1. open dev tool
1. fill the dates
1. click the cancel button (icon with "x")
1. see the console

### What is expected?

The first parameter of `onChange` and `onCalendarChange` should be same.
I'm not sure how it is actually, but I think `[null, null]` makes scence.

[In the document](https://www.npmjs.com/package/rc-picker#rangepicker), the type of the `onChange` should be `(value: [moment], formatString: [string, string]) => void` (in the docs, it is written as `Function(value:[moment], formatString: [string, string])`). `value` can't be `null`.

### What is actually happening?

The first parameter of `onChange` and `onCalendarChange` are different.
`onChange` ... `null`
`onCalendarChange` ... `[null, null]`

| Environment | Info |
| --- | --- |
| rc-picker | 4.1.1 |
| React | 18.2.0 |
| System | macOS 14.0 |
| Browser | Google Chrome Version 121.0.6167.139 |

**Comment by tnyo43** [comment]
Same things happens in ant-design because it depends on this library https://github.com/ant-design/ant-design/issues/47404

**Comment by zombieJ** [comment]
It's by design.

The `onChange` event focus on the **value** level. Clear operation is always same:
* RangePicker: `null` not `[null, null]`
* SinglePicker: `null`
* SinglePicker with multiple selection: `null` not `[null, null, null, ...]`

This is the same logic for every input component or other validation lib to check the Form field has value. But `[xx, xx]` is not.

The `onCalendarChange` event focus on the **value field** level. Which means it will ensure the field level has the value:
* RangePicker: `[valueField, valueField]`
* SinglePicker: `valueField`
* SinglePicker with multiple selection: `[valueField, valueField, valueField, ...]`
